name: momeet
description: "2025_CapstoneProject"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^6.1.1
  image_picker: ^1.0.4
  http: ^1.2.2
  path: ^1.8.3

  flutter_plugin_android_lifecycle: ^2.0.8

  cupertino_icons: ^1.0.8
  table_calendar: ^3.2.0
  carousel_slider: ^5.0.0
  provider: ^6.0.5
  fluttertoast: ^8.2.4
  
  intl: ^0.20.2
  flutter_sound: ^9.2.13  # 녹음용
  permission_handler: ^11.0.0  # 권한 요청
  path_provider: ^2.0.15  # 경로 확인
  url_launcher: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:

  fonts:
    - family: freesentation
      fonts:
        - asset: assets/fonts/Freesentation-4Regular.ttf
          weight: 400
        - asset: assets/fonts/Freesentation-5Medium.ttf
          weight: 500
        - asset: assets/fonts/Freesentation-8ExtraBold.ttf
          weight: 800

    - family: 런드리고딕
      fonts:
        - asset: assets/fonts/런드리고딕-Regular.ttf
          weight: 400
        - asset: assets/fonts/런드리고딕-Bold.ttf
          weight: 700

    - family: jamsil
      fonts:
        - asset: assets/fonts/TheJamsil2Light.ttf
          weight: 200

  assets:
    - assets/mainImg_01.jpg
    - assets/clubAct_01.jpg